Simplify docker usage #2955
Dallinger/Dallinger pull request #3043
Opened 2021-06-22 14:16 UTC by silviot

**WIP** See #2955 

Invoking dallinger to deploy docker images requires the image id to be specified each time.

This PR makes dallinger save the (immutable) image name with hash into the experiment's `config.txt`.

Needs thorough testing and documentation

2021-09-22 18:13 UTC, jessesnyder requested changes
I focused on small things because I don't know enough about the functionality to meaningfully evaluate the big things. :-)

2021-09-22 18:14 UTC, jessesnyder commented on dallinger/config.py
>          globalConfigName = ".dallingerconfig"
(I know you didn't introduce the mixed case; for some reason today was the day I realized it was distracting me.)

2021-09-23 13:20 UTC, silviot commented on dallinger/command_line/docker_ssh.py
> +            # TODO: check that the image has been pushed
It might be confusing for the user if they find themselves in this case. I added the check.

2021-09-23 13:21 UTC, silviot commented on dallinger/command_line/docker_ssh.py
> +def build_and_push_image(f):
Docstring added

2021-09-23 13:30 UTC, silviot commented on tests/test_docker.py
> +def test_add_image_name(tmp_path):
I'm +0 on this (it doesn't bother me much) but I see your point. Switched to `tempdir`.

2021-09-23 13:50 UTC, silviot commented on dallinger/command_line/docker_ssh.py
> +        else f"tls {config.get('contact_email_on_error', 'dallinger@mailnator.com')}"
Good point. I removed the default, added a check, and warned the user in the wrong email case.

2021-09-23 14:20 UTC, silviot commented on dallinger/config.py
> +    ("image_name", six.text_type, [], ""),
Good point

2021-09-23 14:21 UTC, silviot commented on dallinger/config.py
>          globalConfig = os.path.expanduser(os.path.join("~/", globalConfigName))
It does make sense, but I believe it's better to leave it out of this PR discussion

2021-09-23 16:11 UTC, jessesnyder approved these changes
Looks great!

2021-09-23 16:12 UTC, jessesnyder commented
@merge at will, @silviot. :shipit:

2021-09-23 16:34 UTC, merged