Expose directory from the host when deploying with docker
Dallinger/Dallinger pull request #3528
Opened 2021-11-03 16:31 UTC by silviot

See #3140 

## Expose a directory on the host when deploying with `dallinger docker-ssh`
The directory inside the container (the one that the experiment code needs to write to) is always `/var/lib/dallinger`, regardless of experiment id.
Files written to such directory in the container will end up in `/var/lib/dallinger/{{ experiment_id }}` on the host.
The owner of the files will be root, since the dallinger containers currently run the web server and the worker using the `root` user inside the container.

## Motivation and Context
Experiments might need access to a persistent filesystem.

## How Has This Been Tested?
I checked that the container has the expected asset by entering it with `docker exec` and writing a file to `/var/lib/dallinger`.
I didn't yet test the case when the experiment is exported and reimported.

2021-11-04 14:01 UTC, silviot commented
There is currently no support for loading an exported experiment via the `dallinger docker-ssh` command, so I was not able to test it.

2021-11-04 16:11 UTC, alecpm requested changes
This looks simple enough, but I think it probably needs some documentation.

2021-11-04 19:41 UTC, alecpm approved these changes
I guess the docs are part of story #2956, so consider this approved assuming this feature will be covered there.

2021-11-05 13:22 UTC, silviot commented
Also includes changes to make sure deploying via `dallinger docker-ssh deploy --archive ${ARCHIVE_PATH}` preserves the experiment id.

2021-11-10 17:35 UTC, jessesnyder approved these changes
LGTM!

2021-11-22 18:26 UTC, merged